import Head from 'next/head';
import { Rajdhani } from 'next/font/google';
import CardItem from '@/components/carditem';
import { Grid, GridItem } from '@chakra-ui/react';
import Header from '@/components/header';

const roboto = Rajdhani({
  weight: '500',
  subsets: ['latin']
});
export default function Home() {
  return (
    <>
      <Head>
        <title>URA Homes</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={roboto.className}>
        <Header />
      </main>
    </>
  );
}
